name: CI
on:
  push:
    branches: ["main"]
jobs:
  tests:
    name: "Python ${{ matrix.python-version }}"
    runs-on: "ubuntu-latest"
    env:
      USING_COVERAGE: '3.8'
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install build tools"
        run: "python -m pip install -r requirements.txt"
      - name: "Build a wheel from source"
        run: "python setup.py bdist_wheel"
      - name: "Install the current project"
        run: "python -m pip install ./dist/*.whl"
      - name: "Run tests"
        run: "python tests/tests.py"
      - name: Publish distribution 📦 to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
